# Standards: 0.1
---
- name: Restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: True

- name: Reload elasticsearch
  systemd:
    name: elasticsearch
    state: reloaded
    daemon_reload: True

...
