---
- name: Reload elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: reloaded
    daemon_reload: True

- name: Restart elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: True

- name: Restart elasticsearch-exporter
  ansible.builtin.systemd:
    name: elasticsearch-exporter
    state: restarted
    daemon_reload: yes

...
